#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

## use nano for example in crontab -e
export EDITOR="nano"

## less will search case insensitive, don't clear on exit, show colors
export LESS='-RXI +G'

source "${ZDOTDIR:-$HOME}/.zpersonal.zsh"